object Versions {
    const val ACCOMPANIST = "0.23.1"    // Used in compose 1.1.x version
    const val ACTIVITY = "1.4.0"
    const val APPCOMPAT = "1.3.1"
    const val COMPOSE = "1.1.1"
    const val CONSTRAINT_LAYOUT = "2.1.1"
    const val CORE_KTX = "1.6.0"
    const val COROUTINES = "1.6.0"
    const val COIL = "2.0.0-rc02"
    const val DATASTORE = "1.0.0"
    const val FIREBASE = "29.2.0"
    const val GRADLE_PLUGIN = "7.1.3"
    const val HILT = "2.41"
    const val HILT_JETPACK = "1.0.0-alpha03"
    const val JUNIT = "4.13.2"
    const val KOTLIN = "1.6.10"
    const val LIFECYCLE = "2.4.1"
    const val MATERIAL = "1.4.0"
    const val NAVIGATION = "2.4.2"
    const val OKHTTP = "4.9.0"
    const val PLAY_SERVICE_AUTH = "20.0.1"
    const val RETROFIT = "2.9.0"
    const val ROOM = "2.3.0"
    const val SPLASH = "1.0.0-alpha02"
    const val TIMBER = "4.7.1"
    const val WORK = "2.7.1"
}